namespace EventSourcingEngine;

public interface INodeExecutor<TState, TEvent> 
    where TState : class
    where TEvent : class
{
    Cursor<TState, TEvent> Cursor { get; set; }
    HashSet<Type> HandlesEvents { get; set; }
    HashSet<Type> ProducesEvents { get; set; }
    Task<TEvent> ExecuteAsync(TEvent @event, CancellationToken cancellationToken);
    TState TryUpdateState(TEvent @event);
    
    /// <summary>
    /// Method executed after the node has been executed and the state has been updated. Should not modify the state.
    /// Can be used for saving generated event to the database or/and saving state's snapshot
    /// </summary>
    /// <param name="event">Event generated by the node</param>
    /// <param name="cancellationToken">Cancellation token</param>
    Task AfterExecutionAndStateUpdate(TEvent @event, CancellationToken cancellationToken);
}