// <auto-generated />
using System;
using ExampleApp.Postgres;
using ExampleApp.Postgres.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExampleApp.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231164727_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExampleApp.Postgres.Models.ProcessRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProcessRequests");
                });

            modelBuilder.Entity("ExampleApp.Postgres.Models.ProcessRequestEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<ProcessRequestEventPayload>("ProcessRequestEventPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ProcessRequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessRequestId");

                    b.ToTable("ProcessRequestEvents");
                });

            modelBuilder.Entity("ExampleApp.Postgres.Models.ProcessRequestEvent", b =>
                {
                    b.HasOne("ExampleApp.Postgres.Models.ProcessRequest", "ProcessRequest")
                        .WithMany("ProcessRequestEvents")
                        .HasForeignKey("ProcessRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessRequest");
                });

            modelBuilder.Entity("ExampleApp.Postgres.Models.ProcessRequest", b =>
                {
                    b.Navigation("ProcessRequestEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
